name: flutter_prism
description: A syntax highlighting package for Flutter, based on dart_prism.
version: 0.2.0-dev
homepage: https://github.com/chenzhiguang/flutter_prism

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  dart_prism: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
